apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: neath-tan7026-react-certificate
  namespace: neath-tan7026-react
spec:
  secretName: neath-tan7026-react-secret-tls
  commonName: neath-tan7026-react.assessify.org
  dnsNames:
  - neath-tan7026-react.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
